/**:
  ros__parameters:
    fluid_pressure_atm: 89206.11402914838
    magnetic_declination: 10.7
    water_salinity_ppt: 0.0

coug0:
  battery_sub:
    ros__parameters:
      critical_voltage: 14.0

  coug_controls:
    ros__parameters:
      depth_kd: 0.0
      depth_ki: 0.0
      depth_kp: 13.1
      depth_max_output: 25.0
      depth_min_output: -25.0
      heading_kd: 0.0
      heading_ki: 0.0
      heading_kp: 0.0
      heading_max_output: 25.0
      heading_min_output: -25.0
      look_ahead: 5.0
      pid_timer_period: 80
      pitch_kd: 0.0     #HEY O
      pitch_ki: 0.0
      pitch_kp: 0.0
      pitch_max_output: 25.0
      pitch_min_output: -25.0
      theta_max: 25.0

  coug_kinematics:
    ros__parameters:
      demo_mode: false
      left_fin_offset: 0.0
      right_fin_offset: 0.0
      top_fin_offset: 0.0
      trim_ratio: 0.0
  depth_convertor:
    ros__parameters:
      fluid_pressure_atm: 87250.0
  fins_manual:
    ros__parameters:
      command_timer_period: 0.1
      commands: '[100, 0, 0, 0, 0],[10, 0, 0, 0, 100], [5, 0, 0, 0, 0], [10, 0, 0,
        0, 50], [20, 15, 0, 0, 50], [5, 0, 0, 0, 50], [20, 0, 15, 15, 50], [20, 0,
        -15, -15, 50], [5, 0, 0, 0, 50], [20, 15, -15, 15, 50], [5, 0, 0, 0, 0]'
  gps_odom:
    ros__parameters:
      origin.altitude: 1367.0
      origin.latitude: 40.238833
      origin.longitude: -111.742249
  gpsd_client:
    ros__parameters:
      check_fix_by_variance: false
      frame_id: gps
      publish_rate: 10
      use_gps_time: false
  manual_mission:
    ros__parameters:
      command_timer_period: 0.5
      state_1_count: 0
      state_1_depth: 0.0
      state_1_heading: 0.0
      state_1_speed: 0.0
      state_2_count: 0
      state_2_depth: 0.0
      state_2_heading: 0.0
      state_2_speed: 0.0
      state_3_count: 0
      state_3_depth: 0.0
      state_3_heading: 0.0
      state_3_speed: 0.0
