# Created by Clayton Smith, Feb 2025
#
# ROS PARAMETER VALUES FOR ALL VEHICLES AND BASE STATION


#############################################################
#                   Universal Parameters                    #
#############################################################

/**:
  ros__parameters:
    water_salinity_ppt: 0.0 # 0.0 for fresh water, 35.0 for salt water
    # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml?
    magnetic_declination: 10.7 # E is positive, W is negative, 10.70Â° E for Utah Lake

    # the origin should be shared between base station and all robots
    origin.latitude: 40.0717976 # 40.2735 for Utah Lake
    origin.longitude: -111.6002054 # -111.7126 for Utah Lake
    origin.altitude: 1367.00 # from testing

    # mission_start_time: 1739302061  # Time offset to reduce bytes in timestamp

    mission_file_path: '/home/frostlab/config/mission_states.json'