name: Docker Build on Tag

# Trigger only on tag pushes
on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0, v2.1, etc.

jobs:
  build-and-push-vehicle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (only on push or dispatch)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push vehicle image with tag
        uses: docker/build-push-action@v6
        with:
          context: ./
          dockerfile: docker/vehicle/runtime/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cougars:vehicle-${{ github.ref_name }}

  build-and-push-base-station:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (only on push or dispatch)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base station image with tag
        uses: docker/build-push-action@v6
        with:
          context: ./
          dockerfile: docker/base_station/runtime/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cougars:base_station-${{ github.ref_name }}